### ISSUE TITLE
command 'skpm create' failed

### ISSUE THREAD

**Issue by leadream** [skpm/skpm#115]
the command `skpm create dir` failed with status 1.

below is my env

* node version 8.6.0
* npm version 5.6.0
* yarn version v1.3.2

I tried to log the error by modifying the code in usr/local/bin and got this err:
```
{
  Error: Exited with status 1
    at closeArgsToError (/usr/local/lib/node_modules/skpm/node_modules/cross-spawn-promise/lib/index.js:20:16)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/skpm/node_modules/cross-spawn-promise/lib/index.js:76:19)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
  exitStatus: 1,
  stdout: null,
  stderr: null 
}


```

**Comment by mathieudutour** [comment]
hum the actual error is `null` 🤔 

Could you try a few thing to see if we can pinpoint the issue?
* `skpm --help` should you the help
* `skpm create` should prompt you to select a destination
* `skpm create existing/dir` should refuse to create a new project because there is already a dir

**Comment by leadream** [comment]
@mathieudutour these 3 commands work as expected, but `create` will abort when Installing dependencies.

**Comment by mathieudutour** [comment]
oh interesting. Can you do a `npm install` in the new directory to see where it's failing?

**Comment by leadream** [comment]
![image](https://user-images.githubusercontent.com/12868055/35191166-ead8e574-feae-11e7-91f4-e4a658c52951.png)

`yarn install` worked but `npm install` didn't. Here is the main error information in log file:

```
1263 silly resolveWithNewModule invariant@2.2.2 checking installable status
1264 http fetch GET 304 https://registry.npm.taobao.org/globals 63ms (from cache)
1265 silly fetchPackageMetaData error for globals@^9.18.0 Unexpected end of JSON input while parsing near '...":false,"tarball":"ht'
1266 silly saveTree sketch@0.1.0
...
...
...
1266 silly saveTree   ├── webpack@3.10.0
1266 silly saveTree   ├── yargs@9.0.1
1266 silly saveTree   └── yesno@0.0.1
1267 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...":false,"tarball":"ht'
1267 verbose stack     at JSON.parse (<anonymous>)
1267 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-better-errors/index.js:7:17)
1267 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
1267 verbose stack     at <anonymous>
1267 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
1268 verbose cwd /Users/leadream/sketch
1269 verbose Darwin 17.2.0
1270 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
1271 verbose node v8.6.0
1272 verbose npm  v5.6.0
1273 error Unexpected end of JSON input while parsing near '...":false,"tarball":"ht'
1274 verbose exit [ 1, true ]
```

**Comment by mathieudutour** [comment]
hum it says that `globals@^9.18.0` has broken metadata but I just checked and it looks fine. You are fetching it from your cache, maybe it's corrupted? 🤔

**Comment by leadream** [comment]
@mathieudutour yeah, you're right. I cleaned npm cache and it works. Thanks for your help.
