### ISSUE TITLE
Can't build after updating to builder 0.5.4

### ISSUE THREAD

**Issue by rodi01** [skpm/skpm#151]
After I updated the @skpm/builder I can't no longer build the project. 

I'm getting the following error: 

```
Error while building ./commandRenameLayer.js
./src/commandRenameLayer.js
Module build failed: Error: Cannot find module 'babel-preset-react' from '/Users/rodrigo/Developer/RenameIt'
- If you want to resolve "react", use "module:react"
- Did you mean "@babel/react"?
    at Function.module.exports [as sync] (/Users/rodrigo/Developer/RenameIt/node_modules/resolve/lib/sync.js:42:15)
    at resolveStandardizedName (/Users/rodrigo/Developer/RenameIt/node_modules/@babel/core/lib/config/files/plugins.js:104:31)
    at resolvePreset (/Users/rodrigo/Developer/RenameIt/node_modules/@babel/core/lib/config/files/plugins.js:57:10)
    at loadPreset (/Users/rodrigo/Developer/RenameIt/node_modules/@babel/core/lib/config/files/plugins.js:76:18)
    at createDescriptor (/Users/rodrigo/Developer/RenameIt/node_modules/@babel/core/lib/config/config-descriptors.js:154:21)
    at /Users/rodrigo/Developer/RenameIt/node_modules/@babel/core/lib/config/config-descriptors.js:106:12
    at Array.map (<anonymous>)
    at createDescriptors (/Users/rodrigo/Developer/RenameIt/node_modules/@babel/core/lib/config/config-descriptors.js:105:27)
    at createPresetDescriptors (/Users/rodrigo/Developer/RenameIt/node_modules/@babel/core/lib/config/config-descriptors.js:97:10)
    at /Users/rodrigo/Developer/RenameIt/node_modules/@babel/core/lib/config/config-descriptors.js:83:14
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! RenameIt@3.7.3 build: skpm-build
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the RenameIt@3.7.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Node - v9.10.1
npm - v5.8.0

Thanks

**Comment by mathieudutour** [comment]
hum `babel-preset-react` is not used anymore. Do you have a custom .babelrc file maybe?

**Comment by rodi01** [comment]
I don't have a .babelrc but I think it could be related to the webpack.skpm.config.js. 

Probably here: 
```
  config.module.rules.push({
    test: /\.jsx?$/,
    exclude: /(node_modules|bower_components)/,
    loader: "babel-loader",
    query: {
      presets: ["react"],
      plugins: ["react-html-attrs", "transform-class-properties"],
    },
  })
```

**Comment by thiagolimaop** [comment]
@mathieudutour, if a have a custom .babelrc file with the config:

`{
  "presets": ["@babel/preset-env", "@babel/preset-react"]
}
`
How do i have to proceed?

**Comment by mathieudutour** [comment]
The default config is the same: https://github.com/skpm/skpm/blob/master/packages/babel-preset/index.js. Any reason to use a custom one?
