### ISSUE TITLE
skpm create my-plugin 创建插件报错

### ISSUE THREAD

**Issue by mrme2014** [skpm/skpm#163]
$ npm install -g skpm
$ skpm create my-plugin
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module '../build/Release/keytar.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/skpm/node_modules/keytar/lib/keytar.js:1:76)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)

**Comment by mrme2014** [comment]
how can i resolve   and fix it?
