### ISSUE TITLE
Throw error when I use skpm. module.js:549

### ISSUE THREAD

**Issue by andex** [skpm/skpm#166]
Hi, I installed skpm from `npm install -g skpm`. And after I tried to create the project, but I got this message:

$ skpm create test
module.js:549
    throw err;
    ^
Error: Cannot find module '../build/Release/keytar.node'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/skpm/node_modules/keytar/lib/keytar.js:1:76)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

Can anybody explain me what is going on?

**Comment by andex** [comment]
Deleted and reinstall node and npm, and it is working now.
