### ISSUE TITLE
TypeError: Cannot read property 'full_name' of undefined

### ISSUE THREAD

**Issue by jasondonnette** [skpm/skpm#170]
When using `skpm publish`, everything works up until creating the pull request to add to the plugin directory. 

I have the permissions `repo` and `delete_repo` enabled for the access token.

```
 ERROR TypeError: Cannot read property 'full_name' of undefined
TypeError: Cannot read property 'full_name' of undefined
    at deleteExistingBranch (/Users/twitch/.nvm/versions/node/v10.4.1/lib/node_modules/skpm/lib/utils/github.js:143:72)
    at getOriginBranchSHA (/Users/twitch/.nvm/versions/node/v10.4.1/lib/node_modules/skpm/lib/utils/github.js:148:14)
    at request.then.then.fork (/Users/twitch/.nvm/versions/node/v10.4.1/lib/node_modules/skpm/lib/utils/github.js:174:159)
From previous event:
    at forkUpstream (/Users/twitch/.nvm/versions/node/v10.4.1/lib/node_modules/skpm/lib/utils/github.js:174:146)
    at getCurrentUpstreamPluginJSON.then.res (/Users/twitch/.nvm/versions/node/v10.4.1/lib/node_modules/skpm/lib/utils/github.js:248:16)
From previous event:
    at Object.addPluginToPluginsRegistryRepo (/Users/twitch/.nvm/versions/node/v10.4.1/lib/node_modules/skpm/lib/utils/github.js:246:43)
    at /Users/twitch/.nvm/versions/node/v10.4.1/lib/node_modules/skpm/lib/commands/publish.js:234:32
    at Generator.next (<anonymous>)
    at step (/Users/twitch/.nvm/versions/node/v10.4.1/lib/node_modules/skpm/lib/commands/publish.js:72:191)
    at /Users/twitch/.nvm/versions/node/v10.4.1/lib/node_modules/skpm/lib/commands/publish.js:72:361
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
```

**Comment by mathieudutour** [comment]
oops sorry about that, I just published a new version that should fix it
