### ISSUE TITLE
No Sketch application found.

### ISSUE THREAD

**Issue by Rawnly** [skpm/skpm#184]
Hi guys, that's happens when I try to run `yarn start` or `npm start` on a plugin.

```
➜ yarn start
yarn run v1.9.4
$ skpm-build --watch --run
🖨  Copied src/manifest.json in 6ms
🛠  Copied assets/placeholder.png
⛏  Copied assets/icon.png
No Sketch application found.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Below the log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/federicovitale/.nvm/versions/node/v10.9.0/bin/node',
1 verbose cli   '/Users/federicovitale/.nvm/versions/node/v10.9.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@6.2.0
3 info using node@v10.9.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle unsplash@1.0.1~prestart: unsplash@1.0.1
6 info lifecycle unsplash@1.0.1~start: unsplash@1.0.1
7 verbose lifecycle unsplash@1.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle unsplash@1.0.1~start: PATH: /Users/federicovitale/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/federicovitale/Desktop/unsplash-sketchplugin/node_modules/.bin:/Users/federicovitale/.nvm/versions/node/v10.9.0/bin:/Users/federicovitale/.yarn/bin:/Users/federicovitale/.config/yarn/global/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle unsplash@1.0.1~start: CWD: /Users/federicovitale/Desktop/unsplash-sketchplugin
10 silly lifecycle unsplash@1.0.1~start: Args: [ '-c', 'skpm-build --watch --run' ]
11 silly lifecycle unsplash@1.0.1~start: Returned: code: 1  signal: null
12 info lifecycle unsplash@1.0.1~start: Failed to exec start script
13 verbose stack Error: unsplash@1.0.1 start: `skpm-build --watch --run`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/federicovitale/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/federicovitale/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
14 verbose pkgid unsplash@1.0.1
15 verbose cwd /Users/federicovitale/Desktop/unsplash-sketchplugin
16 verbose Darwin 18.0.0
17 verbose argv "/Users/federicovitale/.nvm/versions/node/v10.9.0/bin/node" "/Users/federicovitale/.nvm/versions/node/v10.9.0/bin/npm" "run" "start"
18 verbose node v10.9.0
19 verbose npm  v6.2.0
20 error code ELIFECYCLE
21 error errno 1
22 error unsplash@1.0.1 start: `skpm-build --watch --run`
22 error Exit status 1
23 error Failed at the unsplash@1.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I have both **Sketch** and **Sketch Beta** in my `/Applications` folder

**Comment by mathieudutour** [comment]
fixed in https://github.com/skpm/skpm/commit/b2a3204bf1e97ea2e06cf467eed779b99188b387

(you could also specify the path to the Sketch app with `skpm-build --watch --run --app=PATH/TO/APP.app`)

**Comment by miadwang** [comment]
This is the default config:
```
const DEFAULT_CONFIG = {
  sketchPath: '/Applications/Sketch.app',
  pluginDirectory: `${homedir}/Library/Application Support/com.bohemiancoding.sketch3/Plugins/`,
  logsLocation: `${homedir}/Library/Logs/com.bohemiancoding.sketch3/Plugin Output.log`,
  plugins: {},
}
```

If skpm cannot find appPath and has to use the hardcoded path, it will use config.sketchApp, but the property name for the path in default config is "sketchPath", not "sketchApp". So appPath will be undefined and error shows.
```
// resort to use a hardcoded path
  if (!appPath) {
    appPath = getConfig().sketchApp
  }
```
