### ISSUE TITLE
unable to install skpm on Mac

### ISSUE THREAD

**Issue by Sun1996** [skpm/skpm#192]
I am unable to install SKPM on mac using the following command
`npm  install -g skpm`
here is the output
```
npm  install -g skpm
/Users/new/.npm-global/bin/skpm -> /Users/new/.npm
global/lib/node_modules/skpm/lib/index.js > keytar@4.3.0 install  /Users/new/.npm-global/lib/node_modules/skpm/node_modules/keytar >  
prebuild-install || node-gyp rebuild
prebuild-install WARN install No prebuilt binaries found (target=11.1.0 runtime=node arch=x64 platform=darwin)
gyp ERR! configure error 
gyp ERR! stack Error: Command failed:
/Users/new/anaconda/anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:387:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close (net.js:611:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/11.1.0/bin/node"  "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/new/.npm-  global/lib/node_modules/skpm/node_modules/keytar
gyp ERR! node -v v11.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@4.3.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:387:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close (net.js:611:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/11.1.0/bin/node"  "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/new/.npm-  global/lib/node_modules/skpm/node_modules/keytar
gyp ERR! node -v v11.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@4.3.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
```

**Comment by lukasholzer** [comment]
which node and npm version?

**Comment by mathieudutour** [comment]
I have a branch ready to remove keytar. Hopefully that will fix it. Will try to push tomorrow

**Comment by Sun1996** [comment]
> 哪个节点和npm版本？
macOC  10.13.6 
npm 6.4.1

**Comment by Sun1996** [comment]
> which node and npm version?

macOS    10.13.6
npm      6.4.1

**Comment by mathieudutour** [comment]
`npm install -g skpm@1.1.10` should work

**Comment by Sun1996** [comment]
thanks !
