### ISSUE TITLE
error while skpm publish

### ISSUE THREAD

**Issue by jorgemartins** [skpm/skpm#211]
when running `skpm publish minor` I get this error ate the _Publishing the plugin on the official plugin directory_ step

```json
⠏ Publishing the plugin on the official plugin directory
✖ ERROR Error: {
  "message": "Update is not a fast forward",
  "documentation_url": "https://developer.github.com/v3/git/refs/#update-a-reference",
  "statusCode": 422,
  "request": {
    "method": "PATCH",
    "url": "https://api.github.com/repos/jorgemartins/plugin-directory/git/refs/heads/master",
    "headers": {
      "Accept": "application/vnd.github.v3+json",
      "Authorization": "Token **********",
      "User-Agent": "SKPM-Release-Agent"
    },
    "json": {
      "sha": "f4783d68f0c4930d5696a5b597bb894f1aff0d59"
    }
  }
}
    at getErrorFromBody (/Users/jorgemartins/.nvm/versions/node/v11.10.1/lib/node_modules/skpm/lib/utils/request.js:34:10)
    at Request._callback (/Users/jorgemartins/.nvm/versions/node/v11.10.1/lib/node_modules/skpm/lib/utils/request.js:46:23)
    at Request.self.callback (/Users/jorgemartins/.nvm/versions/node/v11.10.1/lib/node_modules/skpm/node_modules/request/request.js:185:22)
    at Request.emit (events.js:197:13)
    at Request.<anonymous> (/Users/jorgemartins/.nvm/versions/node/v11.10.1/lib/node_modules/skpm/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:197:13)
    at IncomingMessage.<anonymous> (/Users/jorgemartins/.nvm/versions/node/v11.10.1/lib/node_modules/skpm/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:285:13)
    at IncomingMessage.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
```

any idea on how to avoid this?

**Comment by mathieudutour** [comment]
it's because you have a fork of plugin-directory which cannot be updated automatically. Delete it and it should work

**Comment by mathieudutour** [comment]
or you can manually create the PR, at this point the update has already been published
