### ISSUE TITLE
Error while trying to publish

### ISSUE THREAD

**Issue by rodi01** [skpm/skpm#227]
I'm getting the follow error when I try to publish my plugin
```
internal/modules/cjs/loader.js:840
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/usr/local/lib/node_modules/skpm/node_modules/keytar/build/Release/keytar.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 67. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:840:18)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/skpm/node_modules/keytar/lib/keytar.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
```

I've already tried to remove the Skpm folder inside node_modules and re-install it. I'm on the skpm 1.2.0 version

**Comment by mathieudutour** [comment]
try to run
```
npm uninstall -g skpm
npm install -g skpm
```

**Comment by rodi01** [comment]
It worked, thanks!
