### ISSUE TITLE
publish fails with "Reference update failed"

### ISSUE THREAD

**Issue by avk** [skpm/skpm#229]
Hello, first time skpm user (1.2.0) writing [my first Sketch plugin](https://github.com/avk/sketch-tabula-rasa). Thanks for a great tool. 

When publishing for the very first time I saw this error:
```sh
$ skpm publish 0.1.0
? The plugin is not on the plugins registry yet. Do you wish to add it? Yes
⠼ Publishing the plugin on the official plugin directory
✖ ERROR Error: {
  "message": "Reference update failed",
  "documentation_url": "https://developer.github.com/v3/git/refs/#create-a-reference",
  "statusCode": 422,
  "request": {
    "method": "POST",
    "url": "https://api.github.com/repos/avk/plugin-directory/git/refs",
    "headers": {
      "Accept": "application/vnd.github.v3+json",
      "Authorization": "Token **********",
      "User-Agent": "SKPM-Release-Agent"
    },
    "json": {
      "ref": "refs/heads/avk/sketch-tabula-rasa",
      "sha": "2d8fa64c787daeda34b6d579fef7416fe03c2ae4"
    }
  }
}
Error: {
  "message": "Reference update failed",
  "documentation_url": "https://developer.github.com/v3/git/refs/#create-a-reference",
  "statusCode": 422,
  "request": {
    "method": "POST",
    "url": "https://api.github.com/repos/avk/plugin-directory/git/refs",
    "headers": {
      "Accept": "application/vnd.github.v3+json",
      "Authorization": "Token **********",
      "User-Agent": "SKPM-Release-Agent"
    },
    "json": {
      "ref": "refs/heads/avk/sketch-tabula-rasa",
      "sha": "2d8fa64c787daeda34b6d579fef7416fe03c2ae4"
    }
  }
}
    at getErrorFromBody (/usr/local/lib/node_modules/skpm/lib/utils/request.js:34:10)
    at Request._callback (/usr/local/lib/node_modules/skpm/lib/utils/request.js:46:23)
    at Request.self.callback (/usr/local/lib/node_modules/skpm/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/skpm/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/skpm/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)

```

Any thoughts on what I should do? Re-running the publish command doesn't seem to try submitting to the plugins registry…

**Comment by avk** [comment]
I'm wondering if my issue was running publish for the first time with a version number:

```sh
$ skpm publish 0.1.0
```

vs 

```sh
$ skpm publish
```

**Comment by mathieudutour** [comment]
hum no I think it's because maybe you already had a fork of https://github.com/sketchplugins/plugin-directory and skpm is getting confused because the fork isn't in a state it'd expect (yeah the whole process is pretty fragile, hopefully changing soon)
