### ISSUE TITLE
Confused about skpm versions

### ISSUE THREAD

**Issue by bvirlet** [skpm/skpm#286]
Hello,

I'm trying to install and run skpm.

After doing `skpm create localize-screenshots`, `cd localize-screenshots`, I'm having the following error:

```
✗ npm run start

> localize-screenshots@0.1.0 start
> skpm-build --watch --run

🖨  Copied src/manifest.json in 2ms
🛠  Copied assets/icon.png
❗️ Cannot run the plugin automatically for Sketch < 45
/Users/bruno/Documents/_TheGrizzlyLabs/src/sketch-screenshots/localize-screenshots/node_modules/webpack/lib/webpack.js:31
		throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
		      ^

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.plugins[3] should be one of these:
   object { apply, … } | function
   -> Plugin of type object or instanceof Function
   Details:
    * configuration.plugins[3] should be an object.
      -> Plugin instance
    * configuration.plugins[3] should be an instance of function
      -> Function acting as plugin
    at webpack (/Users/bruno/Documents/_TheGrizzlyLabs/src/sketch-screenshots/localize-screenshots/node_modules/webpack/lib/webpack.js:31:9)
    at /Users/bruno/Documents/_TheGrizzlyLabs/src/sketch-screenshots/localize-screenshots/node_modules/@skpm/builder/lib/build.js:148:46
    at Generator.next (<anonymous>)
    at step (/Users/bruno/Documents/_TheGrizzlyLabs/src/sketch-screenshots/localize-screenshots/node_modules/@skpm/builder/lib/build.js:298:191)
    at /Users/bruno/Documents/_TheGrizzlyLabs/src/sketch-screenshots/localize-screenshots/node_modules/@skpm/builder/lib/build.js:298:361
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
```

I checked which version of skpm I have:

```
✗ skpm --version
1.3.1
```

Which seems to be the latest version on npm.js, but dating back from a year ago.

But then I see on your repo that the latest tagged version is 0.10.3.

How can I actually get the latest version of `skpm`? Or is it a different problem that I'm having?

Thanks!

**Comment by mathieudutour** [comment]
there is `skpm` that is used to create a new plugin and publishing it (currently on version 1.3.2) and `skpm-build` that is used to compile a plugin (version 0.7.11). I stopped using tags when I started having multiple library in the same repo.
