### ISSUE TITLE
Builder is crashing because dependencies are old

### ISSUE THREAD

**Issue by cyberalien** [skpm/skpm#304]
Builder is crashing because one of its dependencies requiring legacy OpenSSL provider.

macOS: 13.1
Node.js: 18.12.1

Crash log:
```
> skpm-build

[1/3] 🖨  Copied manifest.json in 2ms
[2/3] 🔩  Copied assets/icon.png
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/node_modules/webpack/lib/NormalModule.js:471:10)
    at /node_modules/webpack/lib/NormalModule.js:503:5
    at /node_modules/webpack/lib/NormalModule.js:358:12
    at /node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /node_modules/babel-loader/lib/index.js:59:71
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**Comment by freeman990** [comment]
Same here, after upgrading Node.js’ LTS(18.12.1), skpm failed with same error.

**Comment by vburzynski** [comment]
I'm getting the same thing in Node 18.12.1

**Comment by vburzynski** [comment]
FYI, downgrading to node v16.19.1 (most recent 16.x version) allowed me to get things working, I didn't try any versions in between though.

**Comment by domhabersack** [comment]
You can also pass the command line option `--openssl-legacy-provider` to Node 17+ to revert to the legacy provider as another (temporary) workaround:

```
NODE_OPTIONS=--openssl-legacy-provider skpm-build
```

**Comment by Vinsea** [comment]
> You can also pass the command line option `--openssl-legacy-provider` to Node 17+ to revert to the legacy provider as another (temporary) workaround:
> 
> ```
> NODE_OPTIONS=--openssl-legacy-provider skpm-build
> ```

hi @domhabersack ,have you ever encountered this problem: #307

**Comment by mathieudutour** [comment]
should be fixed now
