### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by ilteris** [skpm/skpm#69]
I am using react-sketchapp library in order to generate some sketch files. Following their example if I run `npm run render` after npm install below is what I get. 

I installed skpm separately  `npm install -g skpm` to make sure it's installed globally as well.

Appreciate any directions. 

```
> colors@1.0.0 render /Users/ikaplan/Desktop/react-sketchapp/examples/colors
> skpm build --watch --run

/Users/ikaplan/Desktop/react-sketchapp/examples/colors/node_modules/skpm/lib/utils/getSketchVersion.js:11
  .then(function ({ stdout, stderr }) {
                  ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/ikaplan/Desktop/react-sketchapp/examples/colors/node_modules/skpm/lib/skpm-build.js:11:24)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "render"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! colors@1.0.0 render: `skpm build --watch --run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the colors@1.0.0 render script 'skpm build --watch --run'.
npm ERR! This is most likely a problem with the colors package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     skpm build --watch --run
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs colors
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls colors
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ikaplan/Desktop/react-sketchapp/examples/colors/npm-debug.log
```

**Comment by ilteris** [comment]
Well I was running npm 2.15.8, I updated to 3.10.10 and it works 💃
