### ISSUE TITLE
publish fails

### ISSUE THREAD

**Issue by lifeiscontent** [skpm/skpm#75]
when I run skpm publish I get this error.

```
{ Error: Cannot find module '/Users/aaronreisman/n/lib/node_modules/skpm/node_modules/keytar'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Function._require [as require] (/Users/aaronreisman/n/lib/node_modules/skpm/node_modules/lazy-require/source/index.js:99:14)
    at Function.installSync (/Users/aaronreisman/n/lib/node_modules/skpm/node_modules/lazy-require/source/index.js:251:23)
    at Function.sync (/Users/aaronreisman/n/lib/node_modules/skpm/node_modules/lazy-require/source/index.js:56:24)
    at lazyRequire (/Users/aaronreisman/n/lib/node_modules/skpm/node_modules/lazy-require/source/index.js:30:66)
    at lazyRequireKeytar (/Users/aaronreisman/n/lib/node_modules/skpm/lib/utils/auth.js:7:18)
    at Object.getToken (/Users/aaronreisman/n/lib/node_modules/skpm/lib/utils/auth.js:24:20) code: 'MODULE_NOT_FOUND' }
```

**Comment by mathieudutour** [comment]
hum could you try one more time? Maybe the installation timed out or something?

**Comment by lifeiscontent** [comment]
@mathieudutour I tried several times, one thing that did fix it, was when I `cd`d into the node_modules folder and did an npm install. but that shouldn't be a step that is required.

notes: I do have script execution turned off due to security concerns so if skpm is doing anything with postinstall that might be why.

**Comment by lifeiscontent** [comment]
@mathieudutour also, upon further inspection, it looks like keytar is not a dependency of skpm

**Comment by mathieudutour** [comment]
yes it's a lazy dependency: it's only installed when you actually need since it's quite heavy and I didn't want to bloat every plugin

**Comment by mathieudutour** [comment]
I'm re-writing skpm to split the build step and the rest so that the plugin can have the minimal amount of dependencies. I should have something by tonight

**Comment by lifeiscontent** [comment]
@mathieudutour great! Thanks for the awesome open source project btw. 👍

**Comment by mathieudutour** [comment]
I'd love it if you could check out the new readmes before I merge 😄 
https://github.com/skpm/skpm/blob/9c57129bd8e21ad9692e11611617db1920185dde/README.md
https://github.com/skpm/skpm/blob/9c57129bd8e21ad9692e11611617db1920185dde/template/README.md

**Comment by lifeiscontent** [comment]
@mathieudutour this new release looks awesome!

Let me know if there’s anything you’d like me to debug
