### ISSUE TITLE
npm install fails with python 3

### ISSUE THREAD

**Issue by aparajita** [skpm/skpm#78]
If we're using pyenv and the global python is version 3, keytar fails to install.

```text
> keytar@4.0.4 install /Users/aparajita/.nvm/versions/node/v8.7.0/lib/node_modules/skpm/node_modules/keytar
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /Users/aparajita/.pyenv/shims/python2 -c import platform; print(platform.python_version());
gyp ERR! stack pyenv: python2: command not found
gyp ERR! stack 
gyp ERR! stack The `python2' command exists in these Python versions:
gyp ERR! stack   2.7.13
gyp ERR! stack 
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:271:12)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:927:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:348:11)
gyp ERR! stack     at emitOne (events.js:115:13)
gyp ERR! stack     at Socket.emit (events.js:210:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:547:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/aparajita/.nvm/versions/node/v8.7.0/bin/node" "/Users/aparajita/.nvm/versions/node/v8.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/aparajita/.nvm/versions/node/v8.7.0/lib/node_modules/skpm/node_modules/keytar
gyp ERR! node -v v8.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@4.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@4.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by mathieudutour** [comment]
well I can't really do anything here, that's super specific to your machine. Try to check why `/Users/aparajita/.pyenv/shims/python2` doesn't exist?

**Comment by aparajita** [comment]
It doesn't exist because pyenv hasn't created it. Ça c'est la guerre.
